title: "How to vote"
preamble: >
  <p>You need to <a href="/register-to-vote?src=schema">register to vote</a> before you can vote in UK elections or referendums.</p>
  <p>If you’re eligible, you can vote in person on the day of the election at a named polling station. You can also apply for a postal or proxy vote instead.</p>
  <p>There are elections and referendums in England, Scotland and Wales on 6 May 2021.</p>

faqs:
  - question: Related content
    answer: >
      <a href="/how-to-vote?src=actions">Voting in person</a>
      <a href="/how-to-vote?src=actions#voting-and-coronavirus">Voting and COVID-19</a>
      <a href="/how-to-vote/voting-by-proxy?src=actions">Ask someone to vote for you</a>

  - question: Ways of voting
    answer: >
      <p>You can vote:</p>
      <ul>
        <li><a href="/how-to-vote/voting-in-person?src=schema">in person at a polling station</a></li>
        <li><a href="/how-to-vote/postal-voting?src=schema">by post</a></li>
        <li>by asking someone else to vote for you (<a href="/how-to-vote/voting-by-proxy?src=schema">voting by proxy</a>)</li>
      </ul>
      <p>You cannot vote online in any elections.</p>

  - question: Eligibility to vote
    answer: >
      <p>You can vote when you're:</p>
      <ul>
        <li>18 years old in England and Northern Ireland</li>
        <li>16 years old in Scottish Parliament and local elections (and other elections when you’re 18)</li>
        <li>16 years old in Welsh Parliament elections (and other elections when you’re 18)</li>
      </ul>
      <h2 id="elections-you-can-vote-in">Elections you can vote in</h2>
      <p><a href="/elections-in-the-uk?src=schema">Different elections have different rules</a> on who can vote.</p>

  - question: Voting and coronavirus (COVID-19)
    answer: >
      <p>Elections and referendums are going ahead during coronavirus (COVID-19), though you may see changes to some processes. You can still vote in person at a polling station.</p>
      <p>If you’re self-isolating, <a rel="external" href="https://www.nhs.uk/conditions/coronavirus-covid-19/people-at-higher-risk/who-is-at-high-risk-from-coronavirus-clinically-extremely-vulnerable/?src=schema">clinically extremely vulnerable</a>, or do not want to go to the polling station, you can <a href="/how-to-vote?src=schema#postal-voting">vote by post</a> or <a href="/how-to-vote?src=schema#voting-by-proxy">vote by proxy</a>.</p>
      <p>You may also be able to get an emergency proxy vote at short notice if you need to self-isolate shortly before or on election day.</p>
      <h2 id="at-the-polling-station">At the polling station</h2>
      <p>Because of COVID-19, there will be safety measures in place at polling stations to help you vote safely (for example, a one-way system or restrictions on the number of people allowed in).</p>
      <p>If you choose to vote in person, make sure you:</p>
      <ul>
        <li>wear a face covering (unless you’re exempt)</li>
        <li>bring your own pen or pencil (there will be clean pencils available at the polling station if you forget to bring your own)</li>
        <li>use the hand sanitiser provided when entering and leaving the polling station</li>
        <li>keep to <a href="/government/publications/how-to-stop-the-spread-of-coronavirus-covid-19/how-to-stop-the-spread-of-coronavirus-covid-19?src=schema">social distancing guidelines</a></li>
      </ul>
      <h2 id="if-you-have-covid-19-symptoms-or-have-been-asked-to-self-isolate">If you have COVID-19 symptoms or have been asked to self-isolate</h2>
      <p>Do not visit the polling station. Apply for an emergency proxy vote instead. Your proxy can also apply if they develop symptoms.</p>
      <p>You can apply until 5pm on 6 May. There are different forms to:</p>
      <ul>
        <li><a rel="external" href="https://www.electoralcommission.org.uk/media/8358?src=schema">apply for an emergency proxy vote in England</a></li>
        <li><a rel="external" href="https://www.electoralcommission.org.uk/media/7528?src=schema">apply for an emergency proxy vote in Scotland</a></li>
        <li><a rel="external" href="https://www.electoralcommission.org.uk/media/8154?src=schema">apply for an emergency proxy vote in Wales</a></li>
      </ul>
      <p>If you’re voting in the Scottish Parliament or Senedd (Welsh Parliament) elections, you must have become aware of the need to self-isolate after 5pm on 27 April.</p>

  - question: Voting in person
    answer: >
      <p>You vote in person at a polling station (usually in a public building, such as a school or local hall).</p>
      <h2 id="your-poll-card">Your poll card</h2>
      <p>You’ll be sent a poll card just before an election telling you when to vote and at which polling station. You can only vote at the polling station location on your card.</p>
      <p>If you have not received a poll card but think you should, contact your local <a href="/get-on-electoral-register?src=schema">Electoral Registration Office</a>.</p>
      <p>You can still vote if you’ve lost your card.</p>

  - question: When you can vote
    answer: >
      <p>Polling stations will be open from 7am to 10pm on 6 May (‘polling day’).</p>

  - question: ID you need to bring
    answer: >
      <p>If you live in England, Wales or Scotland you do not need to bring any identification to vote.</p>
      <p>You do not have to take your poll card with you.</p>

  - question: Voting by post
    answer: >
      <p>You must <a href="/government/publications/apply-for-a-postal-vote?src=schema">apply for a postal vote</a> if you want to vote by post, for example if:</p>
      <ul>
        <li>you’re away from home</li>
        <li>you’re abroad and want to vote in England, Scotland or Wales</li>
      </ul>
      <p>You do not need to give a reason unless you’re voting in Northern Ireland.</p>
      <h2 id="apply-for-a-postal-vote">Apply for a postal vote</h2>
      <p>You can <a href="/government/publications/apply-for-a-postal-vote?src=schema">apply to vote by post</a> for one of the following:<p>
      <ul>
        <li>a single election on a specific date</li>
        <li>a specific period if you want to vote in England, Scotland or Wales</li>
        <li>permanently</li>
      </ul>
      <p>Arrange to <a href="/how-to-vote/voting-by-proxy?src=schema">vote by proxy</a> if there are under 2 weeks until election day and you have not made arrangements.</p>
      <p>There’s a different form to <a href="https://www.eoni.org.uk/Vote/Voting-by-post-or-proxy">apply to vote by post in Northern Ireland</a>.</p>
      <h3 id="postal-vote-deadlines-for-6-may-elections">Postal vote deadlines for 6 May elections</h3>
      <p>You can no longer apply for a postal vote for the elections on 6 May 2021.</p>

  - question: Voting by proxy
    answer: >
      <p>If you’re unable to vote in person you can ask someone to vote on your behalf. This is called a proxy vote.</p>
      <p>You can only apply for a proxy vote under certain circumstances, including:</p>
      <ul>
        <li>being away on polling day</li>
        <li>having a medical issue or disability</li>
        <li>not being able to vote in person because of work or military service</li>
      </ul>
      <h2 id="how-to-apply-for-a-proxy-vote">How to apply for a proxy vote</h2>
      <p><a href="/government/collections/proxy-voting-application-forms?src=schema">Apply for a proxy vote</a> using a paper form. You need to send it to your local <a href="/contact-electoral-registration-office?src=schema">Electoral Registration Office</a>.</p>
      <p>Usually, you need to apply for a proxy vote at least 6 working days before election day if you want to vote in England, Scotland or Wales.</p>
      <p>You can no longer apply for a proxy vote for the elections on 6 May 2021. You may be able to apply for an emergency proxy vote.</p>
      <p>There’s a different form to <a rel="external" href="http://www.eoni.org.uk/Vote/Voting-by-post-or-proxy?src=schema">apply to vote by proxy in Northern Ireland</a>. Apply at least 14 working days before election day.</p>
      <h3 id="apply-for-an-emergency-proxy-vote">Apply for an emergency proxy vote</h3>
      <p>If the proxy vote deadline has passed you may be able to apply for an emergency proxy vote if you both:</p>
      <ul>
        <li>cannot vote in person because of your employment or a disability</li>
        <li>became aware of this reason after the proxy deadline</li>
      </ul>
      <p>You can apply until 5pm on the day of the election. Fill in a paper form to:</p>
      <ul>
        <li><a rel="external" href="https://www.electoralcommission.org.uk/media/6206?src=schema">apply to vote by emergency proxy based on your employment</a></li>
        <li><a rel="external" href="https://www.electoralcommission.org.uk/media/6205?src=schema">apply to vote by emergency proxy based on your disability</a></li>
      </ul>
      <p>An ‘appropriate person’ (for example your employer or a doctor) must sign the application form. Send it to your local <a href="/contact-electoral-registration-office?src=schema">Electoral Registration Office</a>.</p>
      <p>You can also <a href="/how-to-vote?src=schema#voting-and-coronavirus">apply for an emergency proxy vote if you or your proxy need to self-isolate because of COVID-19</a>.</p>

  - question: Voting from abroad
    answer: >
      <p>How you vote when you’re abroad depends on:</p>
      <ul>
        <li>whether you’ll be abroad temporarily or living abroad</li>
        <li>where you want to vote</li>
      </ul>
      <h2 id="if-youll-be-abroad-temporarily">If you’ll be abroad temporarily</h2>
      <p>You can vote by post or proxy if you’ll be abroad temporarily on election day, for example on holiday or a work trip.</p>
      <h3 id="voting-in-england-scotland-or-wales">Voting in England, Scotland or Wales</h3>
      <p>You can arrange:</p>
      <ul>
        <li>to <a href="/how-to-vote/postal-voting?src=schema">vote by post</a></li>
        <li>for someone else to vote for you (<a href="/how-to-vote/voting-by-proxy?src=schema">vote by proxy</a>)</li>
      </ul>
      <p>If you’re abroad on election day you need to make arrangements in advance. Apply to vote by proxy if the election is less than 2 weeks away and you have not made the arrangements yet.</p>
      <p>Your postal ballot will be sent to the address you’ve chosen no earlier than 16 days before the election. You need to return your ballot before 10pm on polling day.</p>
