yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: node-modules
packageExtensions:
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: '8'
  stylelint-config-standard-scss@*:
    peerDependencies:
      postcss: '8'
  stylelint-config-gds@*:
    peerDependencies:
      postcss: '8'