nodeLinker: node-modules

packageExtensions:
  stylelint-config-gds@*:
    peerDependencies:
      postcss: 8
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: 8
  stylelint-config-standard-scss@*:
    peerDependencies:
      postcss: 8

yarnPath: .yarn/releases/yarn-3.6.0.cjs
