name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main
  
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main
    secrets: inherit
    permissions:
      contents: read
      security-events: write
      actions: read

  lint-scss:
    name: Lint SCSS
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yml@main
    with:
      files: "app/assets/stylesheets/"

  lint-javascript:
    name: Lint JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yml@main
    with:
      files: "'app/assets/javascripts/**/*.js' 'spec/javascripts/**/*.js'"

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-javascript:
    name: Test JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yml@main
    with:
      useWithRails: true

  test-ruby:
    name: Test Ruby
    uses: ./.github/workflows/minitest.yml

